repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff-check

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.20.0
    hooks:
      - id: mypy
        additional_dependencies: [
          beautifulsoup4,
          Flask,
          Flask-FlatPages,
          Frozen-Flask,
          pytest,
          types-Pygments,
          types-PyYAML,
          watchdog,
          Werkzeug,
        ]
        files: .
  - repo: local
    hooks:
    - id: forbid-todos
      name: check for TODOs
      entry: grep -rin "TODO"
      language: system
      # Scan python, templates, and static files
      types_or: [python, html, markdown, css, javascript, toml]
