__all__ = ['compress', 'compress_partitioned']

def compress(css: str, max_linelen: int = 0, preserve_exclamation_comments: bool = True) -> str: ...
def compress_partitioned(css: str, max_linelen: int = 0, max_rules_per_file: int = 4000, preserve_exclamation_comments: bool = True) -> list[str]: ...
