from .imports import PygmentsHtmlFormatter as PygmentsHtmlFormatter
from _typeshed import Incomplete
from io import StringIO

class NamedStringIO(StringIO):
    name: Incomplete
    def __init__(self, content, name) -> None: ...

def force_unicode(value, encoding: str = 'utf-8', errors: str = 'strict'): ...
def pygmented_markdown(text, flatpages: Incomplete | None = None): ...
def pygments_style_defs(style: str = 'default'): ...
